import { createToolConfig } from "@askjeeves/conversion-core";
import { SEO_BRAND_TITLE, SEO_DESCRIPTION } from "./src/seo";

export const toolConfig = createToolConfig({
	id: "webp-tools",
	title: SEO_BRAND_TITLE,
	tagline: SEO_DESCRIPTION,
	sourceFormat: "webp",
	allowsMultiple: true,
	minFiles: 1,
	conversions: [
		{
			id: "webp-png",
			source: "webp",
			target: "png",
			label: "WebP → PNG",
			enabled: true,
			options: "image",
		},
		{
			id: "webp-jpeg",
			source: "webp",
			target: "jpeg",
			label: "WebP → JPEG",
			enabled: true,
			options: "image",
		},
		{
			id: "webp-to-pdf",
			source: "webp",
			target: "pdf",
			label: "Convert to PDF",
			enabled: true,
			options: "none",
		},
		{
			id: "webp-to-base64",
			source: "webp",
			target: "txt",
			label: "Convert to Base64",
			enabled: true,
			options: "none",
		},
		{
			id: "webp-crop",
			source: "webp",
			target: "webp",
			label: "Crop image",
			enabled: true,
			options: "image",
		},
		{
			id: "webp-compress",
			source: "webp",
			target: "webp",
			label: "Compress image",
			enabled: true,
			options: "image",
		},
		{
			id: "webp-compress-batch",
			source: "webp",
			target: "webp",
			label: "Compress images (batch)",
			enabled: true,
			options: "image",
			allowsMultipleInputs: true,
		},
	],
});
